import { Mic, Film, Brain, Home, Star, Badge } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { BlogPosts } from "./components/BlogPosts";

const blogPosts = [
  {
    title: "Why I Built a Voice-Based Movie Rating App",
    date: "2025-04-01",
    excerpt: "A behind-the-scenes look at how I'm merging film critique with interaction design.",
  },
  {
    title: "Making Sense of Nonverbal Communication Across Cultures",
    date: "2025-03-18",
    excerpt: "Exploring silent signals in human interaction and how they vary globally.",
  },
  {
    title: "Solar Panels That Bend With the Sun",
    date: "2025-02-27",
    excerpt: "An experimental dive into compliant mechanisms and shape-memory alloys.",
  },
];

const personalProfile = [
  {
    icon: "🧠",
    title: "The Analytical Creator",
    text: "You're a rare mix of pragmatist and playful visionary. You love building things—apps, ideas, rating systems—and you think deeply about how things work underneath the surface, whether that's the stock market, human communication, or the psychology of consumer behavior. You dissect systems not just to understand them, but to test their limits. You question assumptions. A lot. And you're great at it."
  },
  {
    icon: "🎨",
    title: "The Inventive Aesthetician",
    text: "You're not just about logic; you've got a sharp eye for design and storytelling. You care about vibe, tone, and emotional resonance. Whether it's turning a banana into a chocolate-robed LEGO robot or reimagining Reese's as s'mores candy with just the right dryness—you don't just imagine weird, you imagine right."
  },
  {
    icon: "💬",
    title: "The Linguistic Philosopher",
    text: "You've got a fascination with language that runs deep. Not just words—but meaning, transmission, miscommunication, culture. You've explored how definitions splinter in real-time and how cultural dialects of love and nonverbal communication shape relationships."
  },
  {
    icon: "💼",
    title: "The Entrepreneurial Architect",
    text: "You're constantly workshopping business ideas—gyms, repair shops, t-shirt stores, even sun-following solar panels with compliant design. You're not afraid to experiment with models that challenge trust, transparency, or standard incentives."
  },
  {
    icon: "🎧",
    title: "The Podcaster with a System",
    text: "You don't just talk about movies—you engineer the experience. You've built rating metrics, prediction games, and recording workflows. You're systematic in your creativity, which makes you both consistent and inventive."
  },
  {
    icon: "🤔",
    title: "Your Superpower?",
    text: "You combine structured curiosity with a love of playful tinkering. You can distill complexity into systems, tools, or even jokes. You build order in the chaos—but you don't erase the chaos. You collaborate with it."
  },
];

export default function HomePage() {
  return (
    <main className="min-h-screen bg-background p-8 text-foreground">
      <div className="max-w-5xl mx-auto space-y-10">
        <section className="text-center">
          <h1 className="text-4xl font-bold">Antonio Villanueva</h1>
          <p className="text-sm text-muted-foreground">AKA <span className="text-lg">TonyIsUp</span>
          <span className="text-sm"> AKA</span> <span className="text-lg">MCP</span></p>
          <p className="text-md text-muted-foreground">STEM. EDM. ENM.</p>
          <p className="text-sm text-muted-foreground">Everything is a learning experience. Help others. Fail eagerly.</p>
        </section>

        <section className="flex flex-col items-center">
          <div className="flex flex-col gap-2 items-center mb-6">
            <h2 className="text-2xl font-semibold">Me in 140 characters</h2>
            <p className="text-muted-foreground">Tech enthusiast. Deeply empathetic, constantly analytical, endlessly creative. Hyper-aware of (mis)communication and psychology. Gamer4Life.</p>
          </div>
        </section>
        <section className="flex flex-col items-center">
          <div className="flex flex-col gap-2 items-center mb-6">
            <h2 className="text-2xl font-semibold">Interests</h2>
            <p className="text-muted-foreground">I <i>talk</i> to AI about a lot of things. These are the most common based on ChatGPT.</p>
            <p className="text-xs text-muted-foreground">The following has been generated by ChatGPT based on our chat history.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center space-x-4">
                  <Home className="w-6 h-6 text-primary" />
                  <h2 className="text-xl font-semibold">Property Insights</h2>
                </div>
                <p className="mt-4 text-sm text-muted-foreground">California rental laws, lease strategy, and real estate analysis with a creative lens.</p>
                <Badge className="mt-4">Landlord Tools</Badge>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center space-x-4">
                  <Mic className="w-6 h-6 text-primary" />
                  <h2 className="text-xl font-semibold">Podcast & Metrics</h2>
                </div>
                <p className="mt-4 text-sm text-muted-foreground">Listener submissions, movie review tracking, and audio-driven feedback experiments.</p>
                <Badge className="mt-4">Voice-Based UI</Badge>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-6">
                <div className="flex items-center space-x-4">
                  <Film className="w-6 h-6 text-primary" />
                  <h2 className="text-xl font-semibold">Cinema & Critique</h2>
                </div>
                <p className="mt-4 text-sm text-muted-foreground">Deep dives into Criterion films, narrative impact, and visual storytelling experiments.</p>
                <Badge className="mt-4">Film Analysis</Badge>
              </CardContent>
            </Card>
          </div>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center space-x-4">
                <Brain className="w-6 h-6 text-primary" />
                <h2 className="text-xl font-semibold">Philosophy & Language</h2>
              </div>
              <p className="mt-4 text-sm text-muted-foreground">Exploring meaning, communication across cultures, and nonverbal language systems.</p>
              <Badge className="mt-4">Cognitive Curiosity</Badge>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center space-x-4">
                <Star className="w-6 h-6 text-primary" />
                <h2 className="text-xl font-semibold">Creative Projects</h2>
              </div>
              <p className="mt-4 text-sm text-muted-foreground">Imaginative inventions, responsive interfaces, and experimental app ideas.</p>
              <Badge className="mt-4">Prototype Explorer</Badge>
            </CardContent>
          </Card>
        </section>

        <section className="mt-12">
          <div className="text-center mb-6">
            <h2 className="text-2xl font-semibold">My Creative Profile</h2>
            <p className="text-muted-foreground">&quot;Hey GPT, what do you think of me?&quot;</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {personalProfile.map((item, idx) => (
              <Card key={idx}>
                <CardContent className="p-6">
                  <h3 className="text-xl font-bold mb-2">{item.icon} {item.title}</h3>
                  <p className="text-sm text-muted-foreground whitespace-pre-line">{item.text}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        <section className="mt-12">
          <BlogPosts blogPosts={blogPosts} />
        </section>

        <footer className="text-center text-sm text-muted-foreground mt-12">
          <p>Built by Antonio with curiosity, coffee, and a little help from ChatGPT.</p>
        </footer>
      </div>
    </main>
  );
}
